server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: e8424360e1f3e995fdd636690c17ecd6356d45c2609b3ff39197292f6d2a4afc
    url: jdbc:postgresql://ec2-52-205-61-230.compute-1.amazonaws.com:5432/d15qpk0pnl0c06
    username: rnfyvtoaondqqf
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: Precept-Financial@gmail.com
    password: hndodwzmrzhplfjl

    properties:
      mail:
        smpt:
          auth: true
          starttls:
            enable: true

twilio:
  account_sid: ACb676708f3635d0a9dafbcb393114d0df
  auth_token: ef30ca7c4d92ceb283ac4931c35a03ce
  trial_number: +13254252962